services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB:-app}
      interval: 10s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

volumes:
  database_data: ~
